<?php
/* @var $eventForm Event\Form\EventForm */
$eventForm = $this->eventForm;
$eventForm->prepare();
$eventForm->setAttribute(
    'action', $this->url('event-admin/action', array('action' => 'create'))
);
foreach ($eventForm->getElements() as $element) {
    $element->setLabelAttributes(
        array('style' => 'display: block; width: 200px;')
    );
    $element->setAttributes(array('style' => 'display: block; width: 400px;'));
}
?>
<h1>Event anlegen</h1>
<?php if ($this->message): ?>
    <div class="alert alert-danger"><?php echo $this->message ?></div>
<?php endif; ?>
<?php echo $this->form($eventForm); ?>

<p>
    <a class="btn btn-default" href="<?php echo $this->url('event-admin'); ?>">
        zurück
    </a>
</p>
