<?php
/* @var $event Event\Entity\EventEntity */

$urlCreate = $this->url('event-admin/action', array('action' => 'create'));
?>
<h1>Events verwalten</h1>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Beschreibung</th>
        <th>Datum</th>
        <th>Uhrzeit</th>
        <th>Status</th>
        <th>
            <a href="<?php echo $urlCreate; ?>" class="btn btn-default">
                anlegen
            </a>
        </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->eventList as $event) : ?>
        <?php
        $urlShow = $this->url(
            'event-admin/action',
            array('action' => 'show', 'id' => $event->getId())
        );
        $urlUpdate = $this->url(
            'event-admin/action',
            array('action' => 'update', 'id' => $event->getId())
        );
        $urlDelete = $this->url(
            'event-admin/action',
            array('action' => 'delete', 'id' => $event->getId())
        );
        ?>
        <tr>
            <td><?php echo $event->getId(); ?></td>
            <td><?php echo $event->getName(); ?></td>
            <td><?php echo $event->getDescription(); ?></td>
            <td><?php echo $this->dateFormat(
                    $event->getDate(),
                    IntlDateFormatter::LONG,
                    IntlDateFormatter::NONE
                ); ?></td>
            <td><?php echo $this->dateFormat(
                    $event->getTime(),
                    IntlDateFormatter::NONE,
                    IntlDateFormatter::SHORT
                ); ?></td>
            <td><?php echo $this->eventStatus($event->getStatus()); ?></td>
            <td>
                <a class="btn btn-default" href="<?php echo $urlShow; ?>">
                    anzeigen
                </a>
                <a class="btn btn-default" href="<?php echo $urlUpdate; ?>">
                    bearbeiten
                </a>
                <a class="btn btn-default" href="<?php echo $urlDelete; ?>">
                    löschen
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>