<?php
/* @var $event Event\Entity\EventEntity */
$event = $this->event;
?>
<h1>Event anzeigen</h1>

<table class="table table-bordered">
    <tbody>
    <tr>
        <th>Id</th>
        <td><?php echo $event->getId(); ?></td>
    </tr>
    <tr>
        <th>Name</th>
        <td><?php echo $event->getName(); ?></td>
    </tr>
    <tr>
        <th>Beschreibung</th>
        <td><?php echo $event->getDescription(); ?></td>
    </tr>
    <tr>
        <th>Datum</th>
        <td><?php echo $this->dateFormat(
                $event->getDate(),
                IntlDateFormatter::LONG,
                IntlDateFormatter::NONE
            ); ?></td>
    </tr>
    <tr>
        <th>Uhrzeit</th>
        <td><?php echo $this->dateFormat(
                $event->getTime(),
                IntlDateFormatter::NONE,
                IntlDateFormatter::SHORT
            ); ?></td>
    </tr>
    <tr>
        <th>Status</th>
        <td><?php echo $event->getStatus(); ?></td>
    </tr>
    </tbody>
</table>

<p>
    <a class="btn btn-default" href="<?php echo $this->url('event-admin'); ?>">
        zurück
    </a>
</p>
