<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Event\Entity\EventEntity'             => __DIR__ . '/src/Event/Entity/EventEntity.php',
  'Event\Table\EventTableFactory'        => __DIR__ . '/src/Event/Table/EventTableFactory.php',
  'Event\Table\EventTable'               => __DIR__ . '/src/Event/Table/EventTable.php',
  'Event\Config\EventConfigFactory'      => __DIR__ . '/src/Event/Config/EventConfigFactory.php',
  'Event\Service\EventServiceFactory'    => __DIR__ . '/src/Event/Service/EventServiceFactory.php',
  'Event\Service\EventService'           => __DIR__ . '/src/Event/Service/EventService.php',
  'Event\Hydrator\EventHydrator'         => __DIR__ . '/src/Event/Hydrator/EventHydrator.php',
  'Event\Controller\AdminController'     => __DIR__ . '/src/Event/Controller/AdminController.php',
  'Event\View\Helper\EventStatus'        => __DIR__ . '/src/Event/View/Helper/EventStatus.php',
  'Event\View\Helper\EventStatusFactory' => __DIR__ . '/src/Event/View/Helper/EventStatusFactory.php',
  'Event\Module'                         => __DIR__ . '/Module.php',
);
