<?php /* @var $event Event\Entity\EventEntity */ ?>
    <h1>Veranstaltung buchen</h1>
<?php foreach ($this->eventList as $event) : ?>
    <?php
    $urlBook = $this->url(
        'event-order/action', array('action' => 'book', 'id' => $event->getId())
    );
    $date    = $this->dateFormat(
        $event->getDate(), IntlDateFormatter::LONG, IntlDateFormatter::NONE
    );
    $time    = $this->dateFormat(
        $event->getTime(), IntlDateFormatter::NONE, IntlDateFormatter::SHORT
    );
    ?>
    <div class="row-fluid">
        <div class="well">
            <h2><?php echo $event->getName() ?></h2>
            <p><em>Am <?php echo $date; ?> um <?php echo $time; ?> Uhr</em></p>
            <p><?php echo $event->getDescription() ?></p>
            <p>
                <a href="<?php echo $urlBook ?>" class="btn btn-default">
                    Tickets buchen
                </a>
            </p>
        </div>
    </div>
<?php endforeach; ?>